# !/usr/bin/env python3

#!/usr/bin/env python3

# Main.py file generated by New Project wizard

# Created:   Sun May 3 2020
# Processor: RPI3
# Compiler:  Python 3 (Proteus)

# Modules
from goto import *
import time
import var
import pio
import resource
import sys
sys.path.insert(1, '/Users/Nemo/AppData/Local/Temp/VSM Studio/1c90fece9da44dbaa140c947cc7e2739/Raspberry Pi 3')
import CharLCD as LCD
import time
import datetime

rs = 12
en = 16
D4 = 18
D5 = 23
D6 = 24
D7 = 25
lcd_columns = 16
lcd_rows = 2


# Peripheral Configuration Code (do not edit)
#---CONFIG_BEGIN---
def peripheral_setup () :
# Peripheral Constructors
# Install interrupt handlers
 pass

def peripheral_loop () :
 pass

#---CONFIG_END---

# Main function
def main () :
# Setup
 peripheral_setup()
 lcd = LCD.Adafruit_CharLCD(rs, en, D4, D5, D6, D7, lcd_columns, lcd_rows)
# Infinite loop
 while 1 :
  peripheral_loop()
  s = str(datetime.datetime.now().time().second)
  m = str(datetime.datetime.now().time().minute)
  h = str(datetime.datetime.now().time().hour)
  lcd.message(h + ":" + m + ":" +s)
  time.sleep(1)
  lcd.clear()
  pass
# Command line execution
if __name__ == '__main__' :
   main()
